/* =========================================================
   Curriculum — A Guide to Becoming a Lost Soul in Seoul
   ---------------------------------------------------------
   Each unit is a neighborhood on the map.
   x / y  : position on the map (viewBox 1000 × 700, not to scale)
   fact   : one historical / linguistic / cultural note per unit
   ref    : where the topic sits in the Korean school curriculum
            (국어 교과서 / 어문 규범)
   lessons: kind "lesson" or "mission" (a speaking/writing task)
   ========================================================= */

const LEVELS = {
  A0: { ko: "새벽", en: "Dawn",      color: "#9EA9D6" },
  A1: { ko: "아침", en: "Morning",   color: "#EDB86E" },
  A2: { ko: "한낮", en: "Midday",    color: "#7FB8DD" },
  B1: { ko: "오후", en: "Afternoon", color: "#86B598" },
  B2: { ko: "노을", en: "Sunset",    color: "#E8919F" },
  C1: { ko: "저녁", en: "Evening",   color: "#9A86CF" },
  C2: { ko: "밤",   en: "Night",     color: "#4B4884" }
};

const UNITS = [
  /* ───────────── A0 · 새벽 ───────────── */
  {
    id: "gwanghwamun", place: "광화문", placeEn: "Gwanghwamun", level: "A0", x: 440, y: 238,
    title: "Hangul by design", titleKo: "한글의 원리",
    blurb: "King Sejong stands here for a reason. Start with the alphabet that was engineered, not inherited: every letter tells you how to say it.",
    fact: "Hangul Day (한글날) is October 9, the anniversary of the 1446 proclamation. North Korea celebrates its own version, 조선글날, on January 15, counting from the alphabet's creation instead.",
    ref: ["초등 1학년 국어 — 자음자·모음자, 글자의 짜임", "중학교 국어 — 한글의 창제 원리"],
    lessons: [
      { t: "Five shapes of the mouth", k: "기본자 ㄱ ㄴ ㅁ ㅅ ㅇ",
        s: "The five basic consonants are pictures of the speech organs making that sound.",
        p: ["ㄱ: the back of the tongue lifting to block the throat.", "ㄴ: the tongue tip touching the ridge behind the upper teeth.", "ㅁ: the shape of the mouth. ㅅ: a tooth. ㅇ: the round throat."],
        ex: ["ㄱ 가", "ㄴ 나", "ㅁ 마", "ㅅ 사", "ㅇ 아"] },
      { t: "One more stroke, one more breath", k: "가획의 원리",
        s: "Adding a stroke makes the sound stronger. Learn three letters and you can predict the rest.",
        p: ["ㄴ → ㄷ → ㅌ, ㅁ → ㅂ → ㅍ, ㅅ → ㅈ → ㅊ, ㅇ → ㅎ.", "Doubling a letter makes it tense: ㄲ ㄸ ㅃ ㅆ ㅉ.", "ㄹ is the odd one out (이체자): it doesn't follow the stroke rule."],
        ex: ["ㄱ → ㅋ", "ㄷ → ㅌ", "ㅂ → ㅍ", "ㅈ → ㅊ"] },
      { t: "Heaven, earth, human", k: "모음의 원리 (천지인)",
        s: "All vowels come from three symbols: a dot for heaven, a flat line for earth, a standing line for a person.",
        p: ["ㆍ + ㅡ + ㅣ combine into every vowel.", "Bright vowels (양성 모음) ㅏ ㅗ point outward or up; dark vowels (음성 모음) ㅓ ㅜ point inward or down.", "This bright/dark split comes back later in verb endings (아요/어요)."],
        ex: ["ㅣ + ㆍ → ㅏ", "ㆍ + ㅡ → ㅗ", "ㅗ + ㅏ → ㅘ"] },
      { t: "Building a syllable block", k: "글자의 짜임 (모아쓰기)",
        s: "Letters stack into syllable blocks: first consonant, vowel, and an optional final consonant (받침).",
        p: ["Tall vowels (ㅏ ㅓ ㅣ) sit to the right; flat vowels (ㅗ ㅜ ㅡ) sit below.", "A block always starts with a consonant. ㅇ is the silent placeholder.", "The final consonant goes at the bottom."],
        ex: ["ㅎ + ㅏ + ㄴ = 한", "ㄱ + ㅡ + ㄹ = 글", "ㅇ + ㅗ = 오"] },
      { kind: "mission", t: "Write your name in Hangul", k: "내 이름 한글로 써 보기",
        s: "Turn the sounds of your name into syllable blocks. There is often more than one right answer.",
        p: ["Split your name into sounds, not letters.", "Group each sound into a consonant + vowel (+ final) block.", "Compare with how Korean media spell names like yours."],
        ex: ["Anna → 안나", "Lukas → 루카스", "Sophie → 소피"] }
    ]
  },
  {
    id: "seochon", place: "서촌", placeEn: "Seochon", level: "A0", x: 370, y: 168,
    title: "The sound system", titleKo: "소리의 체계",
    blurb: "Quiet alleys, sharp ears. Learn the sounds English doesn't separate, and the sounds Korean doesn't bother to.",
    fact: "King Sejong was born in this neighborhood in 1397, in a district then called 준수방. A small marker near 통인시장 notes the spot.",
    ref: ["중학교 국어 — 음운의 체계 (자음·모음)", "표준 발음법 제2장 (자음과 모음), 제4장 (받침의 발음)"],
    lessons: [
      { t: "The ten pure vowels", k: "단모음",
        s: "Standard Korean lists ten single vowels, but everyday Seoul speech uses fewer.",
        p: ["ㅏ ㅐ ㅓ ㅔ ㅗ ㅚ ㅜ ㅟ ㅡ ㅣ (표준 발음법 제4항).", "ㅚ and ㅟ may also be pronounced as diphthongs.", "Most speakers no longer distinguish ㅐ and ㅔ: 개 and 게 sound the same."],
        ex: ["개 (dog) = 게 (crab)", "어 vs 오", "으 vs 우"] },
      { t: "Gliding vowels", k: "이중 모음",
        s: "Diphthongs add a y- or w- glide before a vowel. ㅢ has its own pronunciation rules.",
        p: ["y-glide: ㅑ ㅕ ㅛ ㅠ ㅒ ㅖ. w-glide: ㅘ ㅝ ㅙ ㅞ.", "ㅢ after a consonant is read [ㅣ]: 희망 [히망].", "The particle 의 may be read [에]: 우리의 [우리의/우리에]."],
        ex: ["의사 [의사]", "희망 [히망]", "주의 [주의/주이]"] },
      { t: "Plain, tense, aspirated", k: "예사소리·된소리·거센소리",
        s: "Korean contrasts three kinds of consonants where English contrasts two. The difference is breath and tension, not voicing.",
        p: ["Plain (ㄱ ㄷ ㅂ ㅈ ㅅ): relaxed, a little breath.", "Tense (ㄲ ㄸ ㅃ ㅉ ㅆ): tight throat, almost no breath.", "Aspirated (ㅋ ㅌ ㅍ ㅊ): a strong puff. Hold a tissue in front of your mouth to check."],
        ex: ["불 / 뿔 / 풀", "달 / 딸 / 탈", "자다 / 짜다 / 차다"] },
      { t: "Between k and g", k: "평음의 변이음",
        s: "A plain consonant like ㄱ is neither exactly k nor exactly g. It shifts with its neighbors, and Korean ears don't notice, because Korean never uses that difference to tell two words apart.",
        p: ["At the start of a word, ㄱ ㄷ ㅂ ㅈ are voiceless, with a light puff of air: the first ㄱ in 고기 is close to a soft [k].", "Between voiced sounds (vowels and ㄴ ㄹ ㅁ ㅇ) they become voiced: the second ㄱ in 고기 sounds like [g]. The same happens in 바보, 두부, 아저씨.", "ㄹ is a quick flap [ɾ] between vowels (나라) and a clear [l] at the end of a syllable or when doubled (발, 빨래). ㅅ before ㅣ sounds close to English sh (시).", "In Seoul speech today, pitch helps too: syllables starting with an aspirated or tense consonant are said on a higher pitch than those starting with a plain one."],
        ex: ["고기 [kogi]", "바보 [pabo]", "두부 [tubu]", "나라 [naɾa], 달 [tal]", "시 [ɕi]"] },
      { t: "The seven final sounds", k: "받침의 대표음",
        s: "Whatever is written, a syllable can only end on seven sounds, and they are never released.",
        p: ["Only [ㄱ ㄴ ㄷ ㄹ ㅁ ㅂ ㅇ] at the end of a syllable (제8항).", "ㄲ ㅋ → [ㄱ], ㅅ ㅆ ㅈ ㅊ ㅌ ㅎ → [ㄷ], ㅍ → [ㅂ] (제9항).", "That's why 낫, 낮, 낯, 낱 all sound like [낟]."],
        ex: ["부엌 [부억]", "옷 [옫]", "앞 [압]", "산, 말, 밤"] },
      { kind: "mission", t: "Read and write by ear", k: "단어 읽기 · 받아쓰기",
        s: "Read short words aloud, then write words you only hear. Start with one-syllable words like 산, 말, 밤.",
        p: ["Read each word twice: slowly, then naturally.", "Cover the list and write from memory or from a recording.", "Check final consonants first, they cause most mistakes."],
        ex: ["산 · 말 · 밤 · 물 · 집", "나무 · 바다 · 고기", "불 · 뿔 · 풀"] }
    ]
  },
  {
    id: "hongdae", place: "홍대", placeEn: "Hongdae", level: "A0", x: 158, y: 246,
    title: "When letters and sounds disagree", titleKo: "소리와 글자가 다른 낱말",
    blurb: "The music district. Korean is spelled by meaning but spoken by sound, so letters change when they meet. Every rule here has a reason.",
    fact: "홍대 is short for 홍익대학교. Koreans clip long names to their first syllables all the time: 연대 (연세대학교), 고대 (고려대학교). The same habit turns 생일 파티 into 생파.",
    ref: ["초등 1–2학년 국어 — 소리와 글자가 다른 낱말, 받아쓰기", "표준 발음법 제12·13·15·17·18·20·23·29항", "고등 국어(문법) — 음운의 변동"],
    lessons: [
      { t: "When a vowel follows a final", k: "연음 (받침 다음에 모음이 올 때)",
        s: "A final consonant slides over to the next syllable if that syllable starts with a vowel.",
        p: ["The silent ㅇ leaves an empty seat, and the final consonant takes it (제13항).", "Double finals split: the second one moves over.", "Applies across particles and endings: 옷이, 꽃을, 앉아."],
        ex: ["음악 [으막]", "옷이 [오시]", "꽃을 [꼬츨]", "앉아 [안자]"] },
      { t: "ㅅ ㅈ ㅊ ㅌ at the end", k: "받침 ㅅ·ㅈ·ㅊ·ㅌ과 다른 소리",
        s: "These finals all become [ㄷ]. Before a new word that starts with a vowel, the [ㄷ] moves over instead of the original letter.",
        p: ["옷 [옫], 낮 [낟], 꽃 [꼳], 밭 [받].", "Next word starts with a vowel: change first, then link (제15항): 옷 안 [오단].", "ㄷ, ㅌ + 이 become [지], [치] (구개음화, 제17항)."],
        ex: ["꽃 위 [꼬뒤]", "옷 안 [오단]", "같이 [가치]", "밭이 [바치]", "굳이 [구지]"] },
      { t: "Turning into a puff", k: "거센소리로 바뀌는 낱말 · 받침 ㅎ",
        s: "ㅎ merges with ㄱ ㄷ ㅂ ㅈ next to it to make ㅋ ㅌ ㅍ ㅊ. Before a vowel, final ㅎ disappears.",
        p: ["ㄱ/ㄷ/ㅂ/ㅈ + ㅎ (in either order) → ㅋ/ㅌ/ㅍ/ㅊ (제12항).", "Final ㅎ + vowel: ㅎ is silent. 좋아요 [조아요].", "ㄶ, ㅀ + vowel: only ㄴ or ㄹ remains. 많이 [마니]."],
        ex: ["축하 [추카]", "좋다 [조타]", "놓고 [노코]", "입학 [이팍]", "많이 [마니]"] },
      { t: "Finals that turn nasal", k: "콧소리로 바뀌는 받침 (비음화)",
        s: "Before ㄴ or ㅁ, the stop sounds [ㄱ ㄷ ㅂ] become the nasal sounds [ㅇ ㄴ ㅁ].",
        p: ["[ㄱ] → [ㅇ], [ㄷ] → [ㄴ], [ㅂ] → [ㅁ] before ㄴ, ㅁ (제18항).", "That includes ㄷ ㅅ ㅆ ㅈ ㅊ ㅌ ㅎ, since they all sound [ㄷ] first.", "ㄹ after ㅁ, ㅇ becomes [ㄴ] (제19항)."],
        ex: ["국물 [궁물]", "밥만 [밤만]", "있는 [인는]", "꽃망울 [꼰망울]", "종로 [종노]", "음료 [음뇨]"] },
      { t: "When ㄴ becomes ㄹ", k: "유음화",
        s: "ㄴ next to ㄹ turns into [ㄹ], in either order.",
        p: ["ㄴ + ㄹ → [ㄹㄹ], ㄹ + ㄴ → [ㄹㄹ] (제20항).", "Compare with 비음화: here ㄴ wins nothing, ㄹ takes over.", "A few words go the other way: 의견란 [의ː견난]."],
        ex: ["신라 [실라]", "연락 [열락]", "설날 [설랄]", "칼날 [칼랄]"] },
      { t: "Getting tense", k: "된소리되기 (ㄱ·ㄷ·ㅈ → ㄲ·ㄸ·ㅉ)",
        s: "After a final [ㄱ ㄷ ㅂ], the next plain consonant becomes tense.",
        p: ["[ㄱ ㄷ ㅂ] + ㄱ ㄷ ㅂ ㅅ ㅈ → ㄲ ㄸ ㅃ ㅆ ㅉ (제23항).", "Also after verb stems ending in ㄴ, ㅁ: 신고 [신ː꼬], 삼고 [삼ː꼬].", "Some compounds tense without a written sign, which is why 사이시옷 exists (C1)."],
        ex: ["학교 [학꾜]", "식당 [식땅]", "숙제 [숙쩨]", "국밥 [국빱]", "잡지 [잡찌]"] },
      { t: "An extra ㄹ appears", k: "ㄹ 소리가 덧나는 낱말",
        s: "In some compounds a [ㄴ] is added before 이, 야, 여, 요, 유, and after ㄹ it becomes [ㄹ].",
        p: ["Step 1: ㄴ is added (ㄴ 첨가, 제29항).", "Step 2: ㄹ + ㄴ → [ㄹㄹ] (유음화).", "Only in compounds and phrases, not inside simple words."],
        ex: ["물약 [물략]", "서울역 [서울력]", "휘발유 [휘발류]", "알약 [알략]"] },
      { kind: "mission", t: "Dictation challenge", k: "받아쓰기",
        s: "Listen to words that sound different from their spelling and write the spelling. This is how Korean first graders practice too.",
        p: ["Write what the word means, not what you hear.", "Then write the pronunciation in brackets.", "Name the rule for each one."],
        ex: ["[궁물] → 국물", "[가치] → 같이", "[실라] → 신라", "[추카] → 축하"] }
    ]
  },

  /* ───────────── A1 · 아침 ───────────── */
  {
    id: "sinchon", place: "신촌", placeEn: "Sinchon", level: "A1", x: 250, y: 336,
    title: "First sentences", titleKo: "첫 문장",
    blurb: "A university neighborhood full of first meetings. Learn the shape of a Korean sentence and introduce yourself.",
    fact: "Yonsei University's Korean Language Institute (한국어학당) opened here in 1959, the first school in Korea to teach Korean to foreigners.",
    ref: ["초등 국어 — 문장의 짜임 (누가/무엇이 + 어찌하다/어떠하다)", "중학교 국어 — 문장 성분"],
    lessons: [
      { t: "The verb comes last", k: "어순 (주어–목적어–서술어)",
        s: "Korean puts the verb at the end. Everything before it can move, because particles mark each role.",
        p: ["Subject – object – verb: 저는 커피를 마셔요.", "Particles carry the roles, so word order is flexible: 커피를 저는 마셔요 is still clear.", "The subject is often dropped when it's obvious."],
        ex: ["저는 커피를 마셔요.", "민지가 책을 읽어요.", "(저는) 학생이에요."] },
      { t: "Saying what something is", k: "이에요 / 예요, 아니에요",
        s: "Attach 이에요 after a consonant and 예요 after a vowel. The negative is 아니에요.",
        p: ["학생 + 이에요 → 학생이에요.", "의사 + 예요 → 의사예요.", "Negative: N이/가 아니에요."],
        ex: ["저는 학생이에요.", "제 친구는 의사예요.", "저는 한국 사람이 아니에요."] },
      { t: "Topic, subject, object: a first look", k: "은/는 · 이/가 · 을/를",
        s: "Three pairs of particles, each with a consonant form and a vowel form.",
        p: ["은/는 marks what you're talking about (topic).", "이/가 marks who or what does it (subject), often new information.", "을/를 marks the object."],
        ex: ["저는 독일 사람이에요.", "비가 와요.", "빵을 먹어요."] },
      { t: "Having and being there", k: "있어요 / 없어요",
        s: "One verb pair covers existence, location, and possession.",
        p: ["N이/가 있어요: there is / I have.", "N에 있어요: something is located somewhere.", "없어요 is the opposite."],
        ex: ["시간이 있어요.", "가방이 의자에 있어요.", "돈이 없어요."] },
      { kind: "mission", t: "Introduce yourself", k: "자기소개 · 인사 역할극",
        s: "Say your name, where you're from, and what you do. Then act out a first meeting with greetings.",
        p: ["Greeting, name, country, job, closing.", "Practice both 해요체 and the formal 합니다체 version.", "Role-play: meeting a classmate, then a teacher."],
        ex: ["안녕하세요. 저는 안나예요.", "독일에서 왔어요.", "저는 대학생이에요.", "만나서 반가워요."] }
    ]
  },
  {
    id: "yeouido", place: "여의도", placeEn: "Yeouido", level: "A1", x: 320, y: 470,
    title: "Verbs and time", titleKo: "어간과 어미",
    blurb: "An island in the river, built in layers. Korean verbs work the same way: a stem plus endings, stacked in order.",
    fact: "Before the National Assembly and the stock exchange, Yeouido was an airfield. Korea's first airfield opened here in 1916.",
    ref: ["중학교 국어 — 용언의 활용 (어간과 어미)", "초등 국어 — 일기 쓰기"],
    lessons: [
      { t: "Stem plus ending", k: "어간 + 어미",
        s: "Take -다 off the dictionary form and you have the stem. Every ending attaches to it.",
        p: ["먹다 → stem 먹-, 가다 → stem 가-.", "Endings never stand alone, and stems rarely do.", "The order of endings is fixed: stem – (honorific) – (tense) – final ending."],
        ex: ["먹 + 어요", "가 + 았 + 어요", "읽 + 으시 + 었 + 어요"] },
      { t: "Bright and dark endings", k: "-아요 / -어요 (모음 조화)",
        s: "If the stem's last vowel is ㅏ or ㅗ, use 아요; otherwise 어요. 하다 becomes 해요.",
        p: ["ㅏ, ㅗ → 아요: 가요, 봐요.", "Other vowels → 어요: 먹어요, 마셔요.", "Vowels merge when they meet: 가 + 아요 → 가요, 보 + 아요 → 봐요."],
        ex: ["가다 → 가요", "보다 → 봐요", "먹다 → 먹어요", "공부하다 → 공부해요"] },
      { t: "Talking about the past", k: "-았/었-",
        s: "The past tense sits between the stem and the final ending, and follows the same bright/dark rule.",
        p: ["ㅏ, ㅗ → 았: 갔어요, 봤어요.", "Others → 었: 먹었어요.", "하다 → 했어요."],
        ex: ["어제 영화를 봤어요.", "점심을 먹었어요.", "친구하고 공부했어요."] },
      { t: "Not and cannot", k: "안 / 못",
        s: "안 means you don't or won't; 못 means you can't.",
        p: ["안 + verb: choice. 못 + verb: inability.", "With 하다 verbs, put 안/못 before 하다: 공부 안 해요.", "Longer forms come later: -지 않다, -지 못하다."],
        ex: ["커피를 안 마셔요.", "매운 음식을 못 먹어요.", "오늘은 운동 안 했어요."] },
      { kind: "mission", t: "Write a short diary", k: "짧은 일기 쓰기",
        s: "Write five sentences about your day in the past tense. Korean schoolchildren start with exactly this.",
        p: ["When, where, what you did, how it felt.", "Use -았/었- in every sentence.", "Add one negative with 안 or 못."],
        ex: ["오늘 아침에 빵을 먹었어요.", "친구를 만났어요.", "날씨가 좋았어요.", "숙제는 못 했어요."] }
    ]
  },

  /* ───────────── A2 · 한낮 ───────────── */
  {
    id: "noryangjin", place: "노량진", placeEn: "Noryangjin", level: "A2", x: 440, y: 548,
    title: "Particles that place things", titleKo: "조사",
    blurb: "Home of the fish market and the cram schools. Particles tell you where, to whom, and how far, which is everything you need to find your way.",
    fact: "Noryangjin is known for its 공시생, students preparing for the civil service exams, and the 컵밥 (rice in a cup) stalls that feed them cheaply.",
    ref: ["중학교 국어 — 품사 (조사)", "고등 국어(문법) — 격 조사와 보조사"],
    lessons: [
      { t: "에 or 에서?", k: "에 / 에서",
        s: "에 is a point: a destination, a location where something exists, a time. 에서 is a stage where an action happens.",
        p: ["가다/오다 + 에: 학교에 가요.", "있다/없다 + 에: 집에 있어요.", "Action + 에서: 학교에서 공부해요. Also \"from\": 독일에서 왔어요."],
        ex: ["세 시에 만나요.", "도서관에 가요.", "도서관에서 책을 읽어요."] },
      { t: "Direction and means", k: "(으)로",
        s: "(으)로 marks a direction or a means. After a consonant other than ㄹ, use 으로.",
        p: ["Direction: 오른쪽으로 가세요.", "Means: 지하철로 가요, 한국어로 말해요.", "After ㄹ: just 로. 연필로, 서울로."],
        ex: ["왼쪽으로 가세요.", "버스로 왔어요.", "숟가락으로 먹어요."] },
      { t: "To someone, from someone", k: "에게 / 한테 / 께",
        s: "For people and animals, use 에게 (writing) or 한테 (speech). 께 is the honorific version.",
        p: ["에 is for places and things, 에게 for living beings.", "From someone: 에게서 / 한테서.", "To someone you respect: 께."],
        ex: ["친구한테 전화했어요.", "동생에게 선물을 줬어요.", "선생님께 드렸어요."] },
      { t: "Also, only, from, until", k: "도 · 만 · 부터 · 까지",
        s: "These particles add meaning rather than marking a role (보조사), and they replace 은/는, 이/가, 을/를.",
        p: ["도: also. 저도 가요.", "만: only. 물만 마셔요.", "부터 … 까지: from … to (time). 에서 … 까지: from … to (place)."],
        ex: ["저도 학생이에요.", "아홉 시부터 다섯 시까지", "서울에서 부산까지"] },
      { kind: "mission", t: "Ask for directions", k: "길 묻기",
        s: "Ask how to get somewhere, understand the answer, and repeat it back.",
        p: ["Ask politely: 실례지만, … 어디에 있어요?", "Listen for 으로, 에서, and landmarks.", "Confirm: 이 길로 쭉 가면 돼요?"],
        ex: ["실례지만, 노량진역이 어디에 있어요?", "저기에서 오른쪽으로 가세요.", "이 길로 쭉 가면 돼요?"] }
    ]
  },
  {
    id: "banpo", place: "반포", placeEn: "Banpo", level: "A2", x: 584, y: 548,
    title: "Wants and plans", titleKo: "바람과 계획",
    blurb: "Evenings by the river and plans for the weekend. Talk about what you want, what you'll do, and what you enjoy.",
    fact: "The Moonlight Rainbow Fountain on 반포대교 entered the Guinness World Records in 2008 as the longest bridge fountain in the world.",
    ref: ["중학교 국어 — 어미의 종류 (연결 어미·전성 어미)", "초등 국어 — 계획하는 글 쓰기"],
    lessons: [
      { t: "I want to", k: "-고 싶다",
        s: "Stem + 고 싶어요 says what you want to do. For someone else, use 고 싶어해요.",
        p: ["Works with any verb: 가고 싶어요, 먹고 싶어요.", "Talking about a third person: 동생이 가고 싶어해요.", "Past: 가고 싶었어요."],
        ex: ["한강에 가고 싶어요.", "떡볶이를 먹고 싶어요.", "친구가 쉬고 싶어해요."] },
      { t: "Will and probably", k: "-(으)ㄹ 거예요",
        s: "One ending for plans and for guesses. Context tells you which.",
        p: ["Plan: 주말에 영화를 볼 거예요.", "Guess: 내일 비가 올 거예요.", "After a consonant: 을 거예요. 먹을 거예요."],
        ex: ["토요일에 친구를 만날 거예요.", "아마 늦을 거예요.", "점심에 비빔밥을 먹을 거예요."] },
      { t: "In order to", k: "-(으)려고",
        s: "Explains why you do something: stem + (으)려고, then the action.",
        p: ["한국어를 배우려고 학원에 다녀요.", "Plan without the action: -(으)려고 해요.", "Same subject in both parts."],
        ex: ["돈을 모으려고 아르바이트를 해요.", "내일 일찍 일어나려고 해요."] },
      { t: "Turning verbs into things", k: "-는 것 / -기",
        s: "To talk about activities as nouns, add -는 것 (or -기). This is how you describe hobbies.",
        p: ["제 취미는 요리하는 것이에요.", "-기 often appears before 좋아하다, 싫어하다, 쉽다, 어렵다.", "In speech, 것이 shortens to 게: 노래하는 게 좋아요."],
        ex: ["걷는 것을 좋아해요.", "한국어는 읽기가 쉬워요.", "그림 그리는 게 재미있어요."] },
      { kind: "mission", t: "Weekend plans and hobbies", k: "주말 계획 쓰기 · 취미 설명",
        s: "Write a short plan for your weekend, then describe a hobby and why you like it.",
        p: ["Plan: day, place, with whom, what you'll do (-(으)ㄹ 거예요).", "Hobby: what it is (-는 것), how often, why.", "Add one wish with -고 싶다."],
        ex: ["토요일에 친구하고 반포 한강공원에 갈 거예요.", "제 취미는 사진 찍는 것이에요.", "언젠가 제주도에 가고 싶어요."] }
    ]
  },
  {
    id: "gangnam", place: "강남", placeEn: "Gangnam", level: "A2", x: 700, y: 604,
    title: "Numbers and requests", titleKo: "수와 부탁",
    blurb: "Shops, cafés, and price tags. Korean has two number systems, and knowing which one to use is half of ordering anything.",
    fact: "강남 (江南) simply means “south of the river”. In 2012, 강남스타일 became the first YouTube video to reach a billion views.",
    ref: ["중학교 국어 — 품사 (수사·수 관형사)", "초등 국어 — 높임 표현 (-(으)세요)"],
    lessons: [
      { t: "Two ways to count", k: "고유어 수 · 한자어 수",
        s: "Native numbers (하나, 둘, 셋) count things and hours. Sino-Korean numbers (일, 이, 삼) handle dates, minutes, money, and phone numbers.",
        p: ["Hours are native, minutes are Sino-Korean: 세 시 삼십 분.", "Before a counter, 하나 둘 셋 넷 → 한 두 세 네.", "Prices are Sino-Korean: 만 오천 원."],
        ex: ["세 시 삼십 분", "삼월 십오일", "만 오천 원"] },
      { t: "Counting words", k: "단위를 나타내는 말",
        s: "Korean counts with a counter word, like \"two cups of\" in English but for almost everything.",
        p: ["Thing + number + counter: 사과 두 개.", "개 (things), 명 (people), 잔 (cups), 권 (books), 병 (bottles), 장 (sheets).", "Animals: 마리. Respected people: 분."],
        ex: ["커피 두 잔", "학생 세 명", "책 한 권", "고양이 네 마리"] },
      { t: "Please do", k: "-(으)세요",
        s: "A polite request, also the honorific form of a statement. Context decides.",
        p: ["Request: 여기 앉으세요.", "Honorific statement: 선생님이 바쁘세요.", "Some verbs change: 먹다 → 드세요, 자다 → 주무세요, 있다 → 계세요."],
        ex: ["천천히 말하세요.", "여기 앉으세요.", "맛있게 드세요."] },
      { t: "Do it for me", k: "-아/어 주세요",
        s: "Asks someone to do something for you. Noun + 주세요 means \"give me\".",
        p: ["Noun + 주세요: 물 주세요.", "Verb + 아/어 주세요: 다시 말해 주세요.", "Softer: -아/어 주시겠어요?"],
        ex: ["아이스 아메리카노 한 잔 주세요.", "포장해 주세요.", "좀 깎아 주세요."] },
      { kind: "mission", t: "Order and shop", k: "식당 주문 · 쇼핑하기",
        s: "Order food for two people, then buy something, asking the price and a different size.",
        p: ["Order with N + number + counter + 주세요.", "Ask the price: 얼마예요?", "Ask for another option: 다른 색 있어요?"],
        ex: ["김치찌개 두 개 주세요.", "이거 얼마예요?", "더 큰 사이즈 있어요?", "카드로 계산할게요."] }
    ]
  },

  /* ───────────── B1 · 오후 ───────────── */
  {
    id: "jamsil", place: "잠실", placeEn: "Jamsil", level: "B1", x: 860, y: 562,
    title: "Irregular verbs", titleKo: "불규칙 활용",
    blurb: "The tallest tower in the city and the most verbs that break the rules. They break them in patterns, though.",
    fact: "잠실 (蠶室) means “silkworm room”. In the Joseon era the state kept silkworm farms here to encourage silk production.",
    ref: ["고등 국어(문법) — 용언의 규칙 활용과 불규칙 활용", "한글 맞춤법 제18항"],
    lessons: [
      { t: "Changes that count as regular", k: "ㄹ 탈락 · ㅡ 탈락",
        s: "School grammar treats these as regular, because they always happen under the same conditions.",
        p: ["ㄹ drops before ㄴ, ㅂ, ㅅ: 살다 → 사니까, 삽니다, 사세요.", "ㅡ drops before 아/어: 쓰다 → 써요, 바쁘다 → 바빠요.", "Every ㄹ-stem and ㅡ-stem behaves this way."],
        ex: ["만들다 → 만드세요", "알다 → 압니다", "예쁘다 → 예뻐요", "크다 → 커요"] },
      { t: "ㅂ irregular", k: "ㅂ 불규칙",
        s: "In many adjectives and some verbs, final ㅂ turns into 우 before a vowel.",
        p: ["덥다 → 더워요, 어렵다 → 어려워요.", "돕다 and 곱다 become 와: 도와요, 고와요.", "Regular ones keep ㅂ: 입다 → 입어요, 좁다 → 좁아요."],
        ex: ["춥다 → 추워요", "맵다 → 매워요", "돕다 → 도와요", "입다 → 입어요"] },
      { t: "ㄷ and ㅅ irregular", k: "ㄷ 불규칙 · ㅅ 불규칙",
        s: "Some ㄷ-stems turn ㄷ into ㄹ, and some ㅅ-stems drop ㅅ, but only before a vowel.",
        p: ["듣다 → 들어요, 걷다 → 걸어요, 묻다 (ask) → 물어요.", "닫다, 받다 stay regular: 닫아요, 받아요.", "낫다 → 나아요, 짓다 → 지어요, but 웃다 → 웃어요."],
        ex: ["음악을 들어요.", "공원을 걸었어요.", "집을 지어요.", "감기가 나았어요."] },
      { t: "르 and ㅎ irregular", k: "르 불규칙 · ㅎ 불규칙",
        s: "르-stems double their ㄹ; ㅎ-adjectives lose ㅎ and change their vowel.",
        p: ["모르다 → 몰라요, 빠르다 → 빨라요, 부르다 → 불러요.", "그렇다 → 그래요, 하얗다 → 하얘요, 빨갛다 → 빨개요.", "좋다 is regular: 좋아요."],
        ex: ["잘 몰라요.", "노래를 불렀어요.", "하늘이 파래요.", "그래요?"] },
      { kind: "mission", t: "Tell a story from your life", k: "경험담 말하기",
        s: "Describe something you once did. Use -아/어 본 적이 있다 and as many irregular verbs as you can.",
        p: ["Start with -아/어 본 적이 있어요?", "Set the scene, say what happened, say how it felt.", "Aim for three irregular verbs."],
        ex: ["한국 음식을 만들어 본 적이 있어요?", "날씨가 너무 더워서 힘들었어요.", "길을 몰라서 사람들한테 물어봤어요."] }
    ]
  },
  {
    id: "seongsu", place: "성수", placeEn: "Seongsu", level: "B1", x: 858, y: 362,
    title: "Joining sentences", titleKo: "문장 잇기",
    blurb: "Old factories turned into workshops. Build long sentences from short ones, by linking them or by fitting one inside another.",
    fact: "Seongsu has been Seoul's shoemaking district for decades, full of small workshops making handmade shoes (수제화). Many of its old factories are now cafés and studios.",
    ref: ["중학교 국어 — 문장의 짜임 (홑문장과 겹문장)", "고등 국어(문법) — 이어진문장과 안은문장"],
    lessons: [
      { t: "Linking clauses", k: "이어진문장 (연결 어미)",
        s: "Connective endings join two clauses: and, but, so, because, if.",
        p: ["-고 (and), -지만 (but), -(으)면 (if).", "-아/어서: cause, no past tense, no commands after it.", "-(으)니까: reason, works with commands and suggestions."],
        ex: ["비가 와서 집에 있었어요.", "비싸지만 맛있어요.", "시간이 있으면 같이 가요.", "추우니까 문 닫으세요."] },
      { t: "Describing a noun with a verb", k: "관형사형 어미 -는 / -(으)ㄴ / -(으)ㄹ",
        s: "In Korean the description comes before the noun. The ending shows time.",
        p: ["-는: now. 먹는 사람 (the person eating).", "-(으)ㄴ: past for verbs, present for adjectives. 먹은 사람, 예쁜 꽃.", "-(으)ㄹ: future or possibility. 먹을 사람."],
        ex: ["제가 읽는 책", "어제 본 영화", "내일 만날 친구", "조용한 카페"] },
      { t: "Sentences inside sentences", k: "안은문장",
        s: "A whole clause can work as a noun, a description, or a quote inside a larger sentence.",
        p: ["As a noun (명사절): 그가 오기를 바랐다.", "As a description (관형절): 내가 만든 케이크.", "As a quote (인용절): 친구가 바쁘다고 했다."],
        ex: ["나는 그가 성공하기를 바란다.", "비가 오는 소리가 좋다.", "선생님이 내일 시험이 있다고 하셨다."] },
      { kind: "mission", t: "Review something you loved", k: "감상문 · 브레인스토밍",
        s: "Brainstorm in Korean first, then write a short review of a film, book, or song.",
        p: ["Brainstorm: write single words and phrases in Korean only.", "Review: what it is, what happens, what you felt, who should see it.", "Use at least one modifying clause and one -아/어서."],
        ex: ["제가 제일 좋아하는 영화는 …이에요.", "주인공이 혼자 서울에 오는 장면이 인상 깊었어요.", "음악이 아름다워서 계속 생각났어요."] }
    ]
  },
  {
    id: "dongdaemun", place: "동대문", placeEn: "Dongdaemun", level: "B1", x: 722, y: 302,
    title: "Speaking with respect", titleKo: "높임 표현",
    blurb: "An old city gate with a futuristic plaza beside it. Honorifics work on three levels at once, and you need all three to write a letter or make a phone call.",
    fact: "동대문's official name is 흥인지문 (興仁之門). It's the only one of the four great gates with four characters; the extra 之 is often said to strengthen the city's east side, which feng shui considered weak.",
    ref: ["초등 국어 — 높임 표현", "고등 국어(문법) — 문법 요소 (높임 표현)", "국립국어원 『표준 언어 예절』"],
    lessons: [
      { t: "Who you're talking to", k: "상대 높임 (종결 표현)",
        s: "The sentence ending shows your relationship with the listener.",
        p: ["Formal: 하십시오체 (합니다) and 해라체 (한다).", "Informal: 해요체 (해요) and 해체 (해).", "하오체 and 하게체 survive mostly in older speech and writing."],
        ex: ["감사합니다.", "고마워요.", "고마워.", "내일 봅시다."] },
      { t: "Who you're talking about", k: "주체 높임 (-(으)시-)",
        s: "When the subject deserves respect, add -(으)시- to the verb and use 께서 instead of 이/가.",
        p: ["선생님께서 오셨어요.", "Special verbs: 있다 → 계시다, 먹다 → 드시다/잡수시다, 자다 → 주무시다.", "Possession uses 있으시다: 시간이 있으세요?"],
        ex: ["할머니께서 주무세요.", "아버지께서 회사에 계세요.", "사장님은 회의가 있으세요."] },
      { t: "Who you're doing it for", k: "객체 높임",
        s: "When the object or recipient deserves respect, the verb itself changes.",
        p: ["주다 → 드리다, 묻다 → 여쭈다/여쭙다, 데리다 → 모시다, 보다 → 뵙다.", "에게 → 께.", "These forms carry respect in their meaning, not in an ending."],
        ex: ["할머니께 선물을 드렸어요.", "선생님께 여쭤볼게요.", "부모님을 모시고 갔어요.", "처음 뵙겠습니다."] },
      { t: "Respectful words and common mistakes", k: "높임의 어휘와 잘못된 높임",
        s: "Some nouns have honorific versions, and things should never be honored instead of people.",
        p: ["나이 → 연세, 이름 → 성함, 집 → 댁, 밥 → 진지.", "Wrong: 커피 나오셨습니다 (the coffee isn't the customer).", "Right: 커피 나왔습니다."],
        ex: ["성함이 어떻게 되세요?", "연세가 어떻게 되세요?", "댁이 어디세요?"] },
      { kind: "mission", t: "Write a letter, make a call", k: "편지 쓰기 · 전화 통화",
        s: "Write a short letter to a teacher, then role-play a phone call to book an appointment.",
        p: ["Letter: greeting, purpose, details, thanks, closing.", "Phone: identify yourself, state the reason, confirm details.", "Check all three levels of 높임 in every sentence."],
        ex: ["선생님, 안녕하세요? 저는 …입니다.", "여보세요, 거기 …이지요?", "다음 주 화요일에 예약하고 싶은데요.", "건강하세요."] }
    ]
  },

  /* ───────────── B2 · 노을 ───────────── */
  {
    id: "daehakro", place: "대학로", placeEn: "Daehak-ro", level: "B2", x: 738, y: 176,
    title: "Grammar that reshapes a sentence", titleKo: "문법 요소",
    blurb: "The theater district, where the same story gets told from different angles. Passive, causative, quotation, and aspect change who does what and how we see it.",
    fact: "대학로 means “university street”. Seoul National University stood here until it moved to Gwanak in 1975, and the small theaters moved in after.",
    ref: ["고등 국어(문법) — 문법 요소 (피동·사동·인용·시간 표현)"],
    lessons: [
      { t: "Things happen", k: "피동 표현",
        s: "Passive verbs shift the focus from who did it to what happened.",
        p: ["Suffixes -이-, -히-, -리-, -기-: 보이다, 먹히다, 열리다, 안기다.", "-아/어지다: 만들어지다, 정해지다.", "-되다 for 하다 nouns: 결정되다, 사용되다."],
        ex: ["문이 열렸어요.", "산이 보여요.", "이 다리는 1980년대에 만들어졌다."] },
      { t: "Making someone do it", k: "사동 표현",
        s: "Causative verbs add a person who causes the action.",
        p: ["Suffixes -이-, -히-, -리-, -기-, -우-, -구-, -추-.", "먹이다, 입히다, 울리다, 웃기다, 비우다, 낮추다.", "-게 하다 works with any verb: 가게 하다."],
        ex: ["아이에게 밥을 먹였어요.", "동생을 웃겼어요.", "소리를 좀 낮춰 주세요.", "학생들을 일찍 가게 했다."] },
      { t: "Reporting what was said", k: "직접 인용 · 간접 인용",
        s: "Indirect quotes change their ending by sentence type.",
        p: ["Statement: -다고. 바쁘다고, 간다고.", "Question: -냐고. Command: -(으)라고. Suggestion: -자고.", "Direct quotes use \"…\"라고."],
        ex: ["친구가 내일 온다고 했어요.", "언제 가냐고 물었어요.", "일찍 자라고 했어요.", "같이 가자고 했어요."] },
      { t: "Tense and aspect", k: "시간 표현 (시제와 동작상)",
        s: "Korean marks not just when, but whether an action is ongoing or its result remains.",
        p: ["-고 있다: in progress. 옷을 입고 있어요 (putting on, or wearing).", "-아/어 있다: resulting state. 의자에 앉아 있어요.", "-았었-: a past situation that no longer holds."],
        ex: ["지금 밥을 먹고 있어요.", "문이 열려 있어요.", "예전에 서울에 살았었어요."] },
      { kind: "mission", t: "Debate script and presentation", k: "토론 대본 · 발표 준비",
        s: "Write a short debate script on a simple topic, then turn your side into a two-minute presentation.",
        p: ["Claim, two reasons, one example, conclusion.", "Quote one source with -다고 하다.", "Use one passive to present facts neutrally."],
        ex: ["저는 … 에 찬성합니다.", "그 이유는 첫째, …기 때문입니다.", "한 조사에 따르면 …다고 합니다.", "이상으로 발표를 마치겠습니다."] }
    ]
  },
  {
    id: "jongno", place: "종로", placeEn: "Jongno", level: "B2", x: 622, y: 258,
    title: "How words are built", titleKo: "단어의 짜임",
    blurb: "The oldest commercial street, and the oldest layers of vocabulary. Learn to take words apart, and you'll read a newspaper twice as fast.",
    fact: "종로 (鐘路) is named after the bell at 보신각, rung every New Year's Eve. Its side alley 피맛골 comes from 피마 (避馬), “avoiding horses”: commoners took it to avoid bowing to officials riding down the main road. The ㅅ in 피맛골 is the 사이시옷 you'll meet in 인사동.",
    ref: ["중학교 국어 — 품사, 단어의 짜임, 어휘의 체계", "고등 국어(문법) — 형태소와 단어 형성"],
    lessons: [
      { t: "The smallest pieces of meaning", k: "형태소",
        s: "Morphemes are the smallest units that carry meaning. Some stand alone, some can't; some carry content, some carry grammar.",
        p: ["자립 형태소 (free) vs 의존 형태소 (bound).", "실질 형태소 (content) vs 형식 형태소 (grammar).", "하늘이 맑다 → 하늘 / 이 / 맑- / -다."],
        ex: ["하늘 / 이 / 맑- / -다", "책 / 을 / 읽- / -었- / -다"] },
      { t: "The nine parts of speech", k: "9품사",
        s: "School grammar sorts every word into nine parts of speech, grouped by function.",
        p: ["체언: 명사, 대명사, 수사. 용언: 동사, 형용사.", "수식언: 관형사, 부사. 관계언: 조사. 독립언: 감탄사.", "Korean adjectives conjugate like verbs: 예뻐요, 예뻤어요."],
        ex: ["새 (관형사) 책", "아주 (부사) 빨리", "아이고 (감탄사)"] },
      { t: "Compounds and derivatives", k: "합성어 · 파생어",
        s: "New words are made by joining two roots (합성어) or adding a prefix or suffix to one (파생어).",
        p: ["합성어: 손 + 목 → 손목, 밤 + 낮 → 밤낮.", "파생어 with a prefix: 풋- + 사과 → 풋사과.", "With a suffix: 먹- + -이 → 먹이, 지우- + -개 → 지우개."],
        ex: ["눈물", "봄비", "맨발", "덮개"] },
      { t: "Native, Sino-Korean, borrowed", k: "고유어 · 한자어 · 외래어",
        s: "Most Korean vocabulary is Sino-Korean, built from reusable Chinese-character roots.",
        p: ["One meaning, three layers: 집 / 가옥 / 하우스.", "Learn a root once, recognize it everywhere: 학(學) → 학교, 학생, 과학, 학습.", "News and academic writing lean heavily on 한자어."],
        ex: ["학교 · 학생 · 과학", "인(人): 한국인, 인간, 인구", "생(生): 학생, 생일, 생활"] },
      { kind: "mission", t: "Summarize a news article", k: "신문 읽고 요약 · 장단점 비교",
        s: "Read a short news article, summarize it in three sentences, and compare the pros and cons of the issue.",
        p: ["Underline every 한자어 root you recognize.", "Summary: who, what, why, in your own words.", "Pros and cons: -는 반면에, -다는 장점이 있다."],
        ex: ["이 기사는 …에 관한 내용이다.", "…다는 장점이 있는 반면에 …다는 단점도 있다.", "내 생각에는 …"] }
    ]
  },

  /* ───────────── C1 · 저녁 ───────────── */
  {
    id: "insadong", place: "인사동", placeEn: "Insadong", level: "C1", x: 544, y: 206,
    title: "Writing it right", titleKo: "국어 규범",
    blurb: "Brushes, ink, and calligraphy shops. Spelling and spacing rules that native speakers get wrong too.",
    fact: "독립신문 (1896) was one of the first publications to separate words with spaces in Hangul. Before that, Korean texts were usually written without spacing.",
    ref: ["한글 맞춤법 (띄어쓰기, 사이시옷)", "표준 발음법 제10·11·29항", "고등 국어(문법) — 국어 규범"],
    lessons: [
      { t: "Spacing", k: "띄어쓰기",
        s: "Words are separated by spaces, but particles attach to the word before them, and bound nouns stand apart.",
        p: ["조사 attaches: 학교에서, 친구도.", "의존 명사 is spaced: 먹을 수 있다, 할 줄 안다, 간 지 오래다.", "Units are spaced: 한 개, 두 명."],
        ex: ["아버지가 방에 들어가신다.", "아버지 가방에 들어가신다.", "할 수 있다", "온 지 삼 년"] },
      { t: "The in-between ㅅ", k: "사이시옷",
        s: "In some compounds a ㅅ is written to show tensing or an added ㄴ sound.",
        p: ["Native + native, or native + Sino-Korean, with a vowel-final first part.", "나뭇잎, 바닷가, 햇빛, 콧물.", "Sino-Korean + Sino-Korean: only six words. 곳간, 셋방, 숫자, 찻간, 툇간, 횟수."],
        ex: ["바닷가 [바다까]", "나뭇잎 [나문닙]", "숫자", "최대값 ✗ → 최댓값"] },
      { t: "Easily confused spellings", k: "헷갈리는 표기",
        s: "Pairs that sound the same or nearly the same but mean different things.",
        p: ["되 / 돼: 돼 = 되어. If 되어 fits, write 돼.", "안 / 않: 안 = 아니, 않 = 아니하.", "-로서 (as, in the capacity of) / -로써 (by means of)."],
        ex: ["안 돼요 / 안 되요 ✗", "가지 않다", "학생으로서", "대화로써 해결하다"] },
      { t: "Double finals and added ㄴ", k: "겹받침과 ㄴ 첨가",
        s: "Each double final keeps one sound, and which one depends on the word. Compounds can gain a ㄴ.",
        p: ["ㄳ ㄵ ㄼ ㄽ ㄾ ㅄ keep the first: 넋 [넉], 넓다 [널따].", "ㄺ ㄻ ㄿ keep the second: 닭 [닥], 삶 [삼].", "Exceptions: 밟다 [밥ː따], 넓죽하다 [넙쭈카다]. ㄴ 첨가: 솜이불 [솜ː니불]."],
        ex: ["읽다 [익따]", "앉다 [안따]", "한여름 [한녀름]", "맨입 [맨닙]"] },
      { kind: "mission", t: "Write a report and an argument", k: "보고서 · 논설문",
        s: "Write a short report on a survey or topic, then an opinion essay. Proofread both for spacing and spelling.",
        p: ["Report: purpose, method, findings, conclusion, written in -다 style.", "Argument: claim, reasons with evidence, counterargument, rebuttal.", "Proofread in two passes: spacing, then spelling."],
        ex: ["본 보고서는 …을/를 목적으로 한다.", "조사 결과 …(으)로 나타났다.", "물론 …다는 의견도 있다. 그러나 …"] }
    ]
  },
  {
    id: "bukchon", place: "북촌", placeEn: "Bukchon", level: "C1", x: 600, y: 128,
    title: "Reading between the lines", titleKo: "담화와 화용",
    blurb: "Hanok rooftops and conversations held at the right volume. What a sentence means depends on who says it, to whom, and what both already know.",
    fact: "눈치, the skill of reading the room, has no single English equivalent. Someone who has it is 눈치가 빠르다; someone who doesn't is 눈치가 없다.",
    ref: ["고등 국어(문법) — 담화의 개념과 특성", "고등 국어(화법) — 토론과 협상"],
    lessons: [
      { t: "은/는 and 이/가, revisited", k: "정보 구조",
        s: "At this level the difference is about information: what's known, what's new, and what's being contrasted.",
        p: ["이/가 can mean \"it's X, not anyone else\": 제가 했어요.", "은/는 can contrast: 커피는 마시는데 차는 안 마셔요.", "Question words take 이/가: 누가 왔어요?"],
        ex: ["제가 했어요. (It was me.)", "저는 했어요. (I did, at least.)", "오늘은 바빠요."] },
      { t: "Endings that carry attitude", k: "종결 어미의 뉘앙스",
        s: "Small endings signal surprise, shared knowledge, or explanation.",
        p: ["-네요: noticing now. -군요: realizing.", "-잖아요: you already know this.", "-거든요: here's the background you're missing."],
        ex: ["눈이 오네요!", "그래서 늦었군요.", "제가 말했잖아요.", "어제 좀 아팠거든요."] },
      { t: "What goes unsaid", k: "생략과 지시 표현",
        s: "Korean drops whatever context supplies and points with 이/그/저.",
        p: ["Subjects and objects disappear when clear: (그거) 먹었어?", "이 (near me), 그 (near you or just mentioned), 저 (over there).", "그 often refers back in a conversation or text."],
        ex: ["밥 먹었어? — 응, 먹었어.", "그거 뭐예요?", "저 사람 누구예요?"] },
      { t: "Politeness as strategy", k: "공손성과 간접 표현",
        s: "Refusing, disagreeing, and asking are softened with hedges and indirect forms.",
        p: ["Hedge with -(으)ㄴ/는데요, -것 같아요.", "Ask indirectly: -아/어 주실 수 있을까요?", "Disagree by acknowledging first: 그 말씀도 맞지만 …"],
        ex: ["그건 좀 어려울 것 같은데요.", "혹시 시간 괜찮으세요?", "좋은 의견이지만, 한 가지만 덧붙이자면 …"] },
      { kind: "mission", t: "Debate and rebut, then interview", k: "시사 토론 · 반박하기 · 인터뷰 답변",
        s: "Take a side on a current issue and rebut an opponent's point politely. Then answer interview questions with structure.",
        p: ["Rebut: restate their point, acknowledge it, counter with evidence.", "Interview: answer, example, link back to the question.", "Use at least two softening strategies."],
        ex: ["말씀하신 부분은 이해합니다만, …", "그 근거에는 한 가지 문제가 있습니다.", "제 경험을 예로 들자면 …"] }
    ]
  },

  /* ───────────── C2 · 밤 ───────────── */
  {
    id: "gyeongbokgung", place: "경복궁", placeEn: "Gyeongbokgung", level: "C2", x: 468, y: 104,
    title: "The history of the language", titleKo: "국어의 역사",
    blurb: "Hangul was created inside these palace walls. Read Korean as it was written five centuries ago, and see why modern spelling looks the way it does.",
    fact: "집현전, the royal research institute whose scholars helped create Hangul, stood inside 경복궁. Today 수정전 (修政殿) occupies its site.",
    ref: ["고등 국어(문법) — 국어의 변천 (고대·중세·근대 국어)", "『훈민정음』 해례본·언해본"],
    lessons: [
      { t: "The Hunminjeongeum", k: "훈민정음",
        s: "Created in 1443 and proclaimed in 1446, with a book explaining its own design.",
        p: ["28 letters: 17 consonants, 11 vowels.", "Four have since disappeared: ㆍ ㅿ ㆆ ㆁ.", "The 해례본 explains the design principles you learned in 광화문."],
        ex: ["나랏말ᄊᆞ미 듕귁에 달아", "(The language of our country differs from China's.)"] },
      { t: "Middle Korean", k: "중세 국어",
        s: "15th-century Korean had pitch accent, an extra vowel, and wrote words the way they sounded across boundaries.",
        p: ["방점 (side dots) marked pitch: none for low, one for high, two for rising.", "ㆍ (아래아) was a real vowel.", "이어적기: a final consonant was written on the next syllable, the opposite of today's 끊어적기."],
        ex: ["사ᄅᆞ미 (= 사람 + 이)", "ᄀᆞᄅᆞᆷ (= 강)"] },
      { t: "From then to now", k: "근대 국어와 현대 국어",
        s: "Sounds merged, spelling was standardized, and modern rules arrived in the 20th century.",
        p: ["ㆍ disappeared from speech and was officially dropped in 1933.", "1933: 한글 맞춤법 통일안 (조선어 학회).", "1988: the current 한글 맞춤법 and 표준어 규정."],
        ex: ["끊어적기: 사람이", "1933 → 1988"] },
      { kind: "mission", t: "Interpret an old text", k: "해석하기",
        s: "Read the opening of the 훈민정음 preface in its 언해본 version and put it into modern Korean.",
        p: ["Identify the old letters and spellings first.", "Write a word-by-word modern version.", "Then a natural modern translation, and an English one."],
        ex: ["나랏말ᄊᆞ미 → 나라의 말이", "듕귁에 달아 → 중국과 달라"] }
    ]
  },
  {
    id: "inwangsan", place: "인왕산", placeEn: "Inwangsan", level: "C2", x: 300, y: 84,
    title: "Literature and your own voice", titleKo: "문학과 문체",
    blurb: "The mountain where Yun Dong-ju walked and wrote. Your last stop is the one where you stop studying the language and start making it yours.",
    fact: "윤동주 lived at the foot of 인왕산 in 1941 and often walked its trails. He died in a Japanese prison in 1945; his poems were published in 1948 as 『하늘과 바람과 별과 시』.",
    ref: ["중학교 국어 — 비유와 상징, 운율", "고등 국어 — 문학 (현대시·고전 시가)"],
    lessons: [
      { t: "Spoken and written styles", k: "구어와 문어",
        s: "Written Korean uses the -다 style, nominal endings, and more Sino-Korean vocabulary.",
        p: ["Narrative and academic writing: 한다, 했다.", "Notices and notes use nominal endings: 회의 있음, 출입 금지.", "Same content, different register: 밥 먹었어 / 식사를 마쳤다."],
        ex: ["오늘 회의 없음.", "본 연구는 …을 분석하였다.", "그는 아무 말도 하지 않았다."] },
      { t: "Figures of speech", k: "비유와 상징",
        s: "Simile, metaphor, personification, and symbol, the building blocks of Korean poetry.",
        p: ["직유: -처럼, -같이, -듯이.", "은유: A는 B이다, with no comparison word.", "의인: giving human actions to things. 상징: a concrete image for an abstract idea."],
        ex: ["호수같이 맑은 눈", "내 마음은 호수요", "바람이 속삭인다"] },
      { t: "Rhythm in Korean verse", k: "운율",
        s: "Korean rhythm comes from counting syllables and grouping phrases, not from stress.",
        p: ["음보: verse is divided into rhythmic groups, often three or four per line.", "시조: three lines, about 45 syllables, with a turn in the final line.", "Modern poets reshape these patterns, for example 김소월's 7·5 rhythm."],
        ex: ["3음보 · 4음보", "시조: 초장 · 중장 · 종장"] },
      { t: "Idioms and proverbs", k: "관용 표현 · 속담",
        s: "Fixed expressions whose meaning isn't the sum of their words.",
        p: ["관용 표현: 발이 넓다 (to know many people), 미역국을 먹다 (to fail an exam).", "속담: 가는 말이 고와야 오는 말이 곱다.", "They show up constantly in headlines and conversation."],
        ex: ["손이 크다", "눈이 높다", "서당 개 삼 년이면 풍월을 읊는다"] },
      { kind: "mission", t: "Write a poem", k: "시 쓰기",
        s: "Write a short poem in Korean about a place in Seoul. Use one image, one figure of speech, and a rhythm you can hear.",
        p: ["Pick one concrete image, not an idea.", "Use one simile or metaphor.", "Read it aloud and count the rhythm groups."],
        ex: ["골목 끝에 걸린 달", "강물처럼 흘러가는 저녁"] }
    ]
  }
];

/* Decorative landmarks on the map (not lessons) */
const MAP_LANDMARKS = {
  namsan: { x: 560, y: 392, label: "남산" }
};
