/* =========================================================
   Built-in dictionary — core vocabulary used across the units
   [word, part of speech, english, level, hanja (optional)]
   Pronunciation is generated by KoEngine.pronounce().
   For anything not listed, the app links out to 한국어기초사전 and
   표준국어대사전 (National Institute of Korean Language).
   ========================================================= */

const DICTIONARY = [
  /* A0–A1 */
  ["산", "noun", "mountain", "A0", "山"], ["말", "noun", "language, words; horse", "A0"], ["밤", "noun", "night; chestnut", "A0"],
  ["물", "noun", "water", "A0"], ["집", "noun", "house, home", "A0"], ["나무", "noun", "tree", "A0"], ["바다", "noun", "sea", "A0"],
  ["고기", "noun", "meat", "A0"], ["나라", "noun", "country", "A0"], ["꽃", "noun", "flower", "A0"], ["옷", "noun", "clothes", "A0"],
  ["부엌", "noun", "kitchen", "A0"], ["음악", "noun", "music", "A0", "音樂"], ["한글", "noun", "the Korean alphabet", "A0"],
  ["안녕하세요", "expression", "hello", "A1"], ["감사합니다", "expression", "thank you (formal)", "A1", "感謝"],
  ["고마워요", "expression", "thank you (polite)", "A1"], ["죄송합니다", "expression", "I'm sorry (formal)", "A1"],
  ["괜찮아요", "expression", "it's okay; I'm fine", "A1"], ["네", "interjection", "yes", "A1"], ["아니요", "interjection", "no", "A1"],
  ["저", "pronoun", "I (humble)", "A1"], ["나", "pronoun", "I (plain)", "A1"], ["이름", "noun", "name", "A1"],
  ["학생", "noun", "student", "A1", "學生"], ["선생님", "noun", "teacher", "A1", "先生"], ["학교", "noun", "school", "A1", "學校"],
  ["대학교", "noun", "university", "A1", "大學校"], ["한국", "noun", "Korea", "A1", "韓國"], ["한국어", "noun", "the Korean language", "A1", "韓國語"],
  ["독일", "noun", "Germany", "A1", "獨逸"], ["사람", "noun", "person", "A1"], ["친구", "noun", "friend", "A1", "親舊"],
  ["회사", "noun", "company", "A1", "會社"], ["의사", "noun", "doctor", "A1", "醫師"], ["시간", "noun", "time", "A1", "時間"],
  ["오늘", "noun", "today", "A1"], ["어제", "noun", "yesterday", "A1"], ["내일", "noun", "tomorrow", "A1", "來日"],
  ["아침", "noun", "morning; breakfast", "A1"], ["점심", "noun", "lunch", "A1", "點心"], ["저녁", "noun", "evening; dinner", "A1"],
  ["밥", "noun", "rice, a meal", "A1"], ["빵", "noun", "bread", "A1"], ["커피", "noun", "coffee", "A1"],
  ["책", "noun", "book", "A1", "冊"], ["가방", "noun", "bag", "A1"], ["의자", "noun", "chair", "A1", "椅子"],
  ["돈", "noun", "money", "A1"], ["가다", "verb", "to go", "A1"], ["오다", "verb", "to come", "A1"],
  ["먹다", "verb", "to eat", "A1"], ["마시다", "verb", "to drink", "A1"], ["보다", "verb", "to see, watch", "A1"],
  ["읽다", "verb", "to read", "A1"], ["쓰다", "verb", "to write; to use; bitter", "A1"], ["하다", "verb", "to do", "A1"],
  ["공부하다", "verb", "to study", "A1", "工夫"], ["만나다", "verb", "to meet", "A1"], ["있다", "adjective", "to exist, to have", "A1"],
  ["없다", "adjective", "to not exist, to not have", "A1"], ["좋다", "adjective", "to be good", "A1"], ["많다", "adjective", "to be many", "A1"],
  ["일기", "noun", "diary", "A1", "日記"], ["날씨", "noun", "weather", "A1"],

  /* A2 */
  ["도서관", "noun", "library", "A2", "圖書館"], ["식당", "noun", "restaurant", "A2", "食堂"], ["역", "noun", "station", "A2", "驛"],
  ["지하철", "noun", "subway", "A2", "地下鐵"], ["버스", "noun", "bus", "A2"], ["길", "noun", "road, way", "A2"],
  ["오른쪽", "noun", "right side", "A2"], ["왼쪽", "noun", "left side", "A2"], ["주말", "noun", "weekend", "A2", "週末"],
  ["취미", "noun", "hobby", "A2", "趣味"], ["계획", "noun", "plan", "A2", "計劃"], ["여행", "noun", "travel", "A2", "旅行"],
  ["영화", "noun", "movie", "A2", "映畫"], ["사진", "noun", "photo", "A2", "寫眞"], ["요리", "noun", "cooking", "A2", "料理"],
  ["가격", "noun", "price", "A2", "價格"], ["얼마", "noun", "how much", "A2"], ["원", "noun", "won (currency)", "A2"],
  ["잔", "counter", "cup, glass", "A2", "盞"], ["개", "counter", "item, piece", "A2", "個"], ["명", "counter", "people", "A2", "名"],
  ["권", "counter", "volumes, books", "A2", "卷"], ["마리", "counter", "animals", "A2"], ["포장", "noun", "packaging; to-go", "A2", "包裝"],
  ["숙제", "noun", "homework", "A2", "宿題"], ["축하", "noun", "congratulations", "A2", "祝賀"], ["국물", "noun", "broth, soup", "A2"],
  ["신라", "noun", "Silla (ancient kingdom)", "A2", "新羅"], ["연락", "noun", "contact", "A2", "連絡"], ["설날", "noun", "Lunar New Year", "A2"],
  ["걷다", "verb", "to walk", "A2"], ["앉다", "verb", "to sit", "A2"], ["주다", "verb", "to give", "A2"],
  ["배우다", "verb", "to learn", "A2"], ["기다리다", "verb", "to wait", "A2"], ["만들다", "verb", "to make", "A2"],
  ["살다", "verb", "to live", "A2"], ["알다", "verb", "to know", "A2"], ["싶다", "adjective", "to want (after -고)", "A2"],
  ["비싸다", "adjective", "to be expensive", "A2"], ["싸다", "adjective", "to be cheap", "A2"], ["맛있다", "adjective", "to be delicious", "A2"],
  ["바쁘다", "adjective", "to be busy", "A2"], ["예쁘다", "adjective", "to be pretty", "A2"], ["크다", "adjective", "to be big", "A2"],
  ["같이", "adverb", "together", "A2"], ["다시", "adverb", "again", "A2"], ["천천히", "adverb", "slowly", "A2"],

  /* B1 */
  ["경험", "noun", "experience", "B1", "經驗"], ["편지", "noun", "letter", "B1", "便紙"], ["전화", "noun", "telephone", "B1", "電話"],
  ["예약", "noun", "reservation", "B1", "豫約"], ["감상", "noun", "appreciation, impression", "B1", "感想"], ["주인공", "noun", "main character", "B1", "主人公"],
  ["장면", "noun", "scene", "B1", "場面"], ["성함", "noun", "name (honorific)", "B1", "姓銜"], ["연세", "noun", "age (honorific)", "B1", "年歲"],
  ["댁", "noun", "home (honorific)", "B1", "宅"], ["진지", "noun", "meal (honorific)", "B1"], ["덥다", "adjective", "to be hot", "B1"],
  ["춥다", "adjective", "to be cold", "B1"], ["어렵다", "adjective", "to be difficult", "B1"], ["쉽다", "adjective", "to be easy", "B1"],
  ["돕다", "verb", "to help", "B1"], ["듣다", "verb", "to listen", "B1"], ["묻다", "verb", "to ask; to bury", "B1"],
  ["낫다", "verb", "to get better; to be better", "B1"], ["짓다", "verb", "to build, make", "B1"], ["모르다", "verb", "to not know", "B1"],
  ["부르다", "verb", "to call; to sing", "B1"], ["빠르다", "adjective", "to be fast", "B1"], ["그렇다", "adjective", "to be so", "B1"],
  ["하얗다", "adjective", "to be white", "B1"], ["파랗다", "adjective", "to be blue", "B1"], ["드리다", "verb", "to give (honorific)", "B1"],
  ["주무시다", "verb", "to sleep (honorific)", "B1"], ["계시다", "verb", "to be, stay (honorific)", "B1"], ["드시다", "verb", "to eat, drink (honorific)", "B1"],
  ["여쭙다", "verb", "to ask (humble)", "B1"], ["뵙다", "verb", "to see, meet (humble)", "B1"], ["모시다", "verb", "to accompany, serve (humble)", "B1"],
  ["인상", "noun", "impression", "B1", "印象"], ["토론", "noun", "debate, discussion", "B1", "討論"],

  /* B2 */
  ["기사", "noun", "article", "B2", "記事"], ["신문", "noun", "newspaper", "B2", "新聞"], ["요약", "noun", "summary", "B2", "要約"],
  ["의견", "noun", "opinion", "B2", "意見"], ["장점", "noun", "advantage", "B2", "長點"], ["단점", "noun", "disadvantage", "B2", "短點"],
  ["발표", "noun", "presentation", "B2", "發表"], ["찬성", "noun", "agreement, support", "B2", "贊成"], ["반대", "noun", "opposition", "B2", "反對"],
  ["조사", "noun", "survey; particle", "B2", "調査 / 助詞"], ["근거", "noun", "grounds, basis", "B2", "根據"], ["결과", "noun", "result", "B2", "結果"],
  ["형태소", "noun", "morpheme", "B2", "形態素"], ["품사", "noun", "part of speech", "B2", "品詞"], ["어휘", "noun", "vocabulary", "B2", "語彙"],
  ["피동", "noun", "passive", "B2", "被動"], ["사동", "noun", "causative", "B2", "使動"], ["인용", "noun", "quotation", "B2", "引用"],
  ["열리다", "verb", "to be opened", "B2"], ["보이다", "verb", "to be seen; to show", "B2"], ["먹이다", "verb", "to feed", "B2"],
  ["웃기다", "verb", "to make laugh", "B2"], ["결정되다", "verb", "to be decided", "B2", "決定"],

  /* C1–C2 */
  ["논설문", "noun", "argumentative essay", "C1", "論說文"], ["보고서", "noun", "report", "C1", "報告書"], ["시사", "noun", "current affairs", "C1", "時事"],
  ["반박", "noun", "rebuttal", "C1", "反駁"], ["띄어쓰기", "noun", "word spacing", "C1"], ["맞춤법", "noun", "spelling rules", "C1"],
  ["표준어", "noun", "standard language", "C1", "標準語"], ["담화", "noun", "discourse", "C1", "談話"], ["공손", "noun", "politeness", "C1", "恭遜"],
  ["납득하다", "verb", "to understand and accept", "C1", "納得"], ["야기하다", "verb", "to cause, bring about", "C1", "惹起"],
  ["완화하다", "verb", "to ease, relieve", "C1", "緩和"], ["고려하다", "verb", "to consider", "C1", "考慮"],
  ["훈민정음", "noun", "Hunminjeongeum (1446)", "C2", "訓民正音"], ["중세", "noun", "the Middle Ages", "C2", "中世"],
  ["방점", "noun", "side dot (tone mark)", "C2", "傍點"], ["문체", "noun", "writing style", "C2", "文體"], ["비유", "noun", "figure of speech", "C2", "比喩"],
  ["상징", "noun", "symbol", "C2", "象徵"], ["운율", "noun", "rhythm (in verse)", "C2", "韻律"], ["시조", "noun", "sijo (verse form)", "C2", "時調"],
  ["속담", "noun", "proverb", "C2", "俗談"], ["관용", "noun", "idiomatic usage", "C2", "慣用"], ["청춘", "noun", "youth", "C2", "靑春"]
];
